### PR TITLE
Fix/dropdown styles

### PR DESCRIPTION
**Pull request by hscheuerle**
Link to Task: https://openforge.teamwork.com/#/tasks/17477929

Change: Jan.8
- fix: remove click listener that was setting active
This was setting active outside of the navbar component, making route changes inside the component a breaking change that was hard to see.

- fix: change anchor to stencil-route-link
This sets the active class based on the stencil router state just like any other route component.

- fix: add less exclusive active class
At some point, the items in the navbar lost their active state, likely due to the nesting of its styles being moved around, so there's a more general style, since setting the active class is likely scoped to the dropdowns there.

Change: Jan.9
- fix: add another active style class because of specificity issue
The styles for the work-with-us button are 4 levels of specificity, which makes styling a generic active style difficult. So I added an active class within that work-with-us definition to set the desired text color when active. Not a bad change considering the difference in appearance between the work-with-us and the other tabs that might diverge in active styling in the future anyway.

### CODE REVIEW

**Comment by hscheuerle** [comment]
https://openforge.teamwork.com/#/tasks/17477929

**Comment by Wholloran** [comment]
Just need to add the select state to the "work with us" button as well.

**Comment by hscheuerle** [comment]
> Just need to add the select state to the "work with us" button as well.

I PM'd some questions on style, the button has the active tag, but it seems like the active styles are gone for that as well. Just asking if the background of the button changes.

**Comment by Wholloran** [comment]
QA Passes

**Pull request merged**
