### PR TITLE
feat(contact): added new design

### PR DESCRIPTION
**Pull request by Fdom92**
https://openforge.teamwork.com/#/tasks/16775310

### CODE REVIEW

**Comment by Wholloran** [comment]
- The placeholder text for the form fields is missing
- The required "*" is missing from "full name" & "email"
- The mailbox icon shows as a broken link on chrome & safari
- The mailbox image needs to be decreased in size to better match the marvel and moved to the right some
- The font & color is wrong for the text. "get in touch" should not be bold
- Add more spacing between the header and the paragraph
- decrease the spacing between the questions to better match the marvel
- decreases  the size for the thank you message slightly so it better matches the marvel 
- Remove Phone & What are you working on from the required list of questions (note, please keep the phone number validator so user enter a valid number if they decided to)
- Add a "passing" state to the current validation that we use to accommodate this marvel screen https://marvelapp.com/3f8d0id/screen/64452741
- When the animation is triggered the user needs to be pushed to the top of the screen


Tablet:
- Per the marvel the contact form should not be full page size is should be 3/4th the size https://marvelapp.com/57djie4/screen/60484377
- the Ipad Pro still shows the side graphic. Need to adjust the breakpoint so this size is considered a tablet. (Note this is the ipad pro via chrome emulator

Mobile:
- The paper fold background looks stretched on mobile devices
- The animation displaying for mobile sizes is the same as desktop, however, per the marvel it should be a different animation

**Comment by luiskcs89** [comment]
Added everything except:
- the Ipad Pro still shows the side graphic. Need to adjust the breakpoint so this size is considered a tablet. (Note this is the ipad pro via chrome emulator -> This one uses the same breakpoints as desktop because of the iPad pro resolution, it is a common thing, we can change it if needed but it takes more work than just using the normal bootstrap breakpoints
- The paper fold background looks stretched on mobile devices -> I don't see we have this asset, asked @JaredKhalil 
- The animation displaying for mobile sizes is the same as desktop, however, per the marvel it should be a different animation -> we need the asset done different to properly resize it for the bkg, asked @JaredKhalil

**Comment by Wholloran** [comment]
oh, I talked with Jared about the different animation, and we agree the current one looks fine. I just forgot to delete that piece of feedback.

**Comment by luiskcs89** [comment]
ok, then I think with these last changes it should be ready for another round of QA

**Comment by Wholloran** [comment]
- The font & color is wrong for the text. "get in touch" should not be bold
- the Ipad Pro still shows the side graphic. Need to adjust the breakpoint so this size is considered a tablet. (Note this is the ipad pro via chrome emulator
- The font & color is wrong for the text. "get in touch" should not be bold (Chrome)
- The corner paper now shows the nonfold version and the fold version (only showing on chrome v79.0.3945.93 and safari v11.0.3 )

**Comment by Fdom92** [comment]
@Wholloran updated PR with fixes

**Comment by Wholloran** [comment]
The above issues all look good. However, the change to breakpoints we made causes an issue on the laptop screens and it's showing the tablet version. Per conversation with Luis lets revert that (having the iPad pro show the desktop version still).

The desktop version looks fine on the iPad pro still and doing custom breakpoints (which would be needed) is out of scope for this ticket.

**Comment by luiskcs89** [comment]
I think I made the revert, can you check that I didn't remove any other important changes that Fer did?

**Comment by Wholloran** [comment]
QA Passes

**Pull request merged**
