### PR TITLE
Feat/partners

### PR DESCRIPTION
**Pull request by luiskcs89**
Task: https://openforge.teamwork.com/#/tasks/16775307

### CODE REVIEW

**Comment by JaredKhalil** [comment]
@luiskcs89 when can we get this deployed for QA?

**Comment by luiskcs89** [comment]
@JaredKhalil what do you mean by deployed to QA? I think it needs to be QA and merged first or am I missing some part of the process?

**Comment by Wholloran** [comment]
@luiskcs89  This wasn't deployed to dev URL with the rest of the features. He was wondering when it would be. I'll be able to check this now though. so disregard his message.

**Comment by Wholloran** [comment]
- The paragraph text for "meet our partners" is the wrong colors
- The "get in touch button is too wide
- Decrease the spacing between "trusted partners" and the partner images
- Move the "interested in partnering with us" section to the left. so there is equal padding on the outside of both the icon and the text.
- There is extra white space on the right side of the get in touch and footer. (there might be another PR for this fix. if so disregard


Mobile:
- The main image is too large on mobile
- Add additional padding below "get in  touch" button to better match the marvel
- Reduce the white space between the last paragraph and "trusted" partners"
- The margins for the text and the carousel are incorrect they should be in line with the image and not the navbar (see marvel for reference https://marvelapp.com/ifbe3gj/screen/64913351

Tablet
- Meet our partner's header is displaying on two lines
- The size of the handshake image is too large and needs to be decreased

**Comment by luiskcs89** [comment]
should be ready for another round of QA

**Comment by Wholloran** [comment]
- Move the "interested in partnering with us" section to the left. so there is equal padding on the outside of both the icon and the text.

Try to mirror it to the marvel for desktop as close of possible https://marvelapp.com/3f8d0id/screen/59793883

**Comment by luiskcs89** [comment]
Ready for another round

**Comment by JaredKhalil** [comment]
Partners(): Contact Us Section doesn’t display correctly [Mobile]

**Comment by luiskcs89** [comment]
should be fixed now

**Comment by Wholloran** [comment]
QA Passes, Please address travis's complaint.

**Pull request merged**
