### PR TITLE
fix(): fix redirect twitter

### PR DESCRIPTION
**Pull request by Fdom92**
https://openforge.teamwork.com/#/tasks/17438393

### CODE REVIEW

**Comment by Wholloran** [comment]
@Fdom92   that PR was merged if you pull develop I can test this tomorrow.

**Comment by Fdom92** [comment]
Ready

**Comment by Wholloran** [comment]
- clicking Jedi's link takes the user to the home page, not his bio page

**Comment by Fdom92** [comment]
That was cause in the other PR was not the needed change, now should be fine @Wholloran

**Comment by Wholloran** [comment]
QA Passes

**Pull request merged**
