### PR TITLE
Feat/search

### PR DESCRIPTION
**Pull request by luiskcs89**
Task: https://openforge.teamwork.com/#/tasks/15486163

### CODE REVIEW

**Comment by Wholloran** [comment]
Getting the following error when running npm i 

Screen Shot 2019-12-30 at 1 32 00 PM

**Comment by luiskcs89** [comment]
fixed

**Comment by Wholloran** [comment]
- Add a little extra padding at the bottom for safari (below the last post, or the load more button
- Remove the blue border and the extra "X' when typing on Safari/chrome

there is no search icon on tablet/mobile right now. if you merge develop it has the new navbar I can test on those two platforms.

**Comment by luiskcs89** [comment]
Should be ready for another round

**Comment by Wholloran** [comment]
The new flow looks good on desktop/tablet/mobile. We just need some small UI tweaks with the Tags. 

- smaller devices will have the tags run off the blog card in the search results if they are longer / have more of them.
- When there are more tags (or tags with longer names like "announcements" there is  no padding on the sides of the letters and they look cramped

IMG_20200103_121721

IMG_20200103_121806

**Comment by luiskcs89** [comment]
fixed

**Pull request merged**
