### PR TITLE
Feat/our work fer

### PR DESCRIPTION
**Pull request by Fdom92**
https://openforge.teamwork.com/#/tasks/16775290

This contains the Our Work page for Desktop and Tablet

### CODE REVIEW

**Comment by Wholloran** [comment]
Jared QA Check 12/27:

Our Work(Landing Page): In Loudcloud project card, the semicolon in the text, "disposable phone number; in over 40 countries!" should be removed

Android Only[found on Samsung Galaxy S8]:
Our Work(): Project images don't fit within screen, are getting pushed out of alignment

**Comment by Wholloran** [comment]
All: 
- Update the "Who we worked with" logo's (The correct icons are on the mobile & tablet marvels the desktop wasn't updated https://marvelapp.com/57djie4/screen/60981427 )
- Update the "got a vision" card, (remove "contact us today line & change button text 
- Update the LC phone images
- Update the Mobile Measures phone images
- The background images for the MM and LC cards are not correct. (their position are incorrect but the asset itself is fine)

Desktop:
- The big gears in the hero image are dark gray but should have a gradient per the marvel
- Reduce the white space between "our work" and the mobile measures card
- "our work" text needs to be centered (vertically) in the header image (right now it's closer to the bottom)

**Comment by PaulPaulDevelops** [comment]
I updated these two comments with the latest commit: 
- Reduce the white space between "our work" and the mobile measures card
- "our work" text needs to be centered (vertically) in the header image (right now it's closer to the bottom)

Adding tag `Code Review Fail` tag as we'll need to migrate the text that is hard-coded into the page into our translation service.

**Comment by PaulPaulDevelops** [comment]
Update the CTA so resolved comment
- Update the "got a vision" card, (remove "contact us today line & change button text

**Comment by Fdom92** [comment]
Updated fixes for :
- Add text into i18n
- Update the LC phone images
- Update the Mobile Measures phone images

For the issues:
- Update the "Who we worked with" logo's -> There are few logo's that are not shared as assets
- The background images for the MM and LC cards are not correct -> Not sure about whats the issue
- The big gears in the hero image are dark gray but should have a gradient per the marvel -> This is the asset, we might need a new asset with the gradient

**Comment by Wholloran** [comment]
- The "view project" buttons are displaying "ourwork.button" and don't redirect

I'll open up sperate tickets to address the asset-related issues.

**Comment by Wholloran** [comment]
QA Passes

**Pull request merged**
