### PR TITLE
fix(cta): cta styles

### PR DESCRIPTION
**Pull request by Fdom92**
https://openforge.teamwork.com/#/tasks/17477285

### CODE REVIEW

**Comment by Wholloran** [comment]
- The style needs to be updated on the CTA on the meet the team page as well 
- Correct text spacing on the CTA on the partner's page 

Screen Shot 2020-01-08 at 1 58 26 PM

**Comment by luiskcs89** [comment]
ready

**Comment by Wholloran** [comment]
- The style for the CTa on the meet the team page still needs to be updated

Screen Shot 2020-01-08 at 2 26 22 PM

**Comment by Fdom92** [comment]
Fixed

**Comment by Wholloran** [comment]
QA Passes

**Pull request merged**
