### PR TITLE
Feat/home

### PR DESCRIPTION
**Pull request by luiskcs89**
Task: https://openforge.teamwork.com/#/tasks/16775286

### CODE REVIEW

**Comment by JaredKhalil** [comment]
Jared QA Check 12/27:

Home(): Hero image alignment isn't appealing, should be centered more
Home(Process): The carousel bar repeats on top of the Learn More button
Home(Process): Slides change too fast, can't read the paragraphs
Home(Process): Not enough padding between "Our Process" title and slides
@luiskcs89

**Comment by luiskcs89** [comment]
@JaredKhalil how much time do you think we need on each slide? also if you can add around how much padding and screenshots of how the images should be more aligned that would be great to avoid back and forth due to missinterpretations.
Thanks

**Comment by luiskcs89** [comment]
Added fixes to carrousel issues (Our Process section), the home unalignment is due to a sizing issue of the animation, passed that to @JaredKhalil to have that asset fixed.

**Comment by Wholloran** [comment]
- "mobile solutions" and "for a digital world" should be the same text style and size https://marvelapp.com/ifbe3gj/screen/60266123
- decrease the size fo the assets in the Our Process section. (the asset size for the first slide looks fine if you want to use that as a guide)

Blog section:
- Change language from "Featured post" to "What's New in Our Blog"
- mobile: move "by author on X/X/XX" to be below the blog image
- Mobile: the blog image and author line should be on a smaller margin than the blog title
- tablet: increase the spacing between the first and second blog slightly
- tablet: the blog image should be the height of the blog title and author lines https://marvelapp.com/57djie4/screen/60483359

Mobile:
- Add additional padding above "Mobile solutions"  
- Decrease space between "experts in and the image above it
- move the app store and play store buttons up slightly so they look more centered below the phone
- The headers in the footer are the same font size as the text, they need to be larger per the marvel (headquarters, work at openforge, the forge)

Tablet:
- 'For a digital world" is displaying as three lines and covers the paragraph text. (this might be fixed with the above headers change mentioned
- The headers in the footer are the same font size as the text, they need to be larger per the marvel (headquarters, work at openforge, the forge)

Footer: 
- address section doesn't match the marvel 
- Read our SLA is on the same line as the hello email link, should be two lines below
- "work at openforge" displays in two lines
- lower the "apply now button per the marvel
- lower the join the forge button per the marvel
-update social media icons

**Comment by Wholloran** [comment]
Per comment on this task https://openforge.teamwork.com/#/tasks/16793915 footers changes are in this PR as well. So I encluded feedback for it as well.

**Comment by luiskcs89** [comment]
Added fixes for:
- "mobile solutions" and "for a digital world" should be the same text style and size
and for blog section except:
- tablet: the blog image should be the height of the blog title and author lines => this happens because of the image ration, we would need to use different sizes on the blog images

**Comment by luiskcs89** [comment]
Should be ready for another round of QA
There are some things like the texts displaying in more lines that depend on the screen size, so it can happen in different sizes, I think it should just behave to look good even if the text takes more lines, but if it doesn't let me know and I can make it smaller to fit more screen sizes.

**Comment by Wholloran** [comment]
Desktop:
- Decrease the size of the "for a digital world" so it's not on three lines 
- The hero image size should be increased https://marvelapp.com/3f8d0id/screen/59789972
Blog section:
- Mobile: the blog image and author line should be on a smaller margin than the blog title https://marvelapp.com/ifbe3gj/screen/60266123
- Tablet: the blog image should be the height of the blog title and author lines https://marvelapp.com/57djie4/screen/60483359

Tablet:
- 'For a digital world" is displaying as three lines and covers the paragraph text. (Might be addressed with font shrink requested above)
IMG_20200102_110055

Footer:
- There should be an additional line break in between the Hello email and "read our SLA" on tablet and desktop
- on mobile, the width of the buttons should be shorter https://marvelapp.com/ifbe3gj/screen/60268230

**Comment by luiskcs89** [comment]
Ready for another round

**Comment by Wholloran** [comment]
The only item left is:
- 'For a digital world" is displaying as three lines and covers the paragraph text. (Might be addressed with font shrink requested above)

Creating a ticket for it and merging

**Pull request merged**
