### PR TITLE
feat(navbar): update styles to match new design

### PR DESCRIPTION
**Pull request by Fdom92**
https://openforge.teamwork.com/#/tasks/16793557

### CODE REVIEW

**Comment by JaredKhalil** [comment]
Jared QA Check 12/27:

Nav(): Nav bar is unaligned and too long
Nav(): Our Work appears twice in Nav Bar
@Fdom92

**Comment by Wholloran** [comment]
So just wanted to toss an update in here. I checked out this PR by itself and the issues mentioned above are not happening. This would be a result of merge conflicts and other features being merged in when Pablo pushed for Jared last week. 

The following are the issue I found specific to this PR:
All:
- Add additional padding between the "work with us" and the magnifying glass
- The open forge logo and the navigation tabs are no aligned (tabs are too high)
- The magnifying glass is too thick

Tablet / mobile:
- The magnifying glass in the search bar is not centered (vertically) (Safari)
- Add a little more padding below the "work with us" button
- Remove the border from the menu button

**Comment by luiskcs89** [comment]
Ready for a new QA round.
For this:
- The magnifying glass is too thick
we would need font awesome pro or a custom icon

**Comment by Wholloran** [comment]
- The magnifying glass in the search bar is now centered on Android but is not safari (vertically)

I'll touch base with the design team about the custom magnifying glass. If they provide one I will open a separate ticket to swap it out.

**Comment by luiskcs89** [comment]
Ready for another round

**Pull request merged**
